# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5af04ac9c0c76a216ec8ec60d8e37cd6f9c63fcd93170af51720f636a238a45d56622810ab94e1878373d42fe0c625c076d0fdf2e4a56c5aab167151eb517b8

test:
  secret_key_base: ea02a9894b8fe212cf4c97a276fb64daf919dca0916ba1710143abf70884d85b8bea744090edb5cd846e87dd8fe2070b83c5a16700bd287b8e50829798a6b1e0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
